solutions:
  - id: 100
    text: Please consider terms that are more inclusive such as allowList/denyList.
  - id: 101
    text: Please consider terms that are more inclusive such as leader/follower/worker/main.
